### ISSUE TITLE
Enchantment glint change not working

### ISSUE THREAD

**Issue by yurtema** [SHsuperCM/CITResewn#211] opened 2022-11-24 11:35 UTC
I'm trying to change enchant glint on netherite helmet (tried other items and armor) like this:
![SCREENSHOT1](https://user-images.githubusercontent.com/86673294/203772590-0cb654c5-f687-4c64-b0b0-a64f348d20ff.jpg)
installed mods also on screenshot

And it doesn't change at all:
![SCREENSHOT2](https://user-images.githubusercontent.com/86673294/203769327-01e85bd4-bbe9-4f24-b4e9-8d216b2895da.png)
![SCREENSHOT3](https://user-images.githubusercontent.com/86673294/203769333-623e9326-d91b-4024-983e-b53196779bcb.png)

logs:
[latest.log](https://github.com/SHsuperCM/CITResewn/files/10083995/latest.log)

Mod is working with everything else (i can change textures and disable glint on everything using global properties)
i tried to change all glint to glow.png by putting it in misc, it did work. So i think problem is not with glow.png
i tried to change using enchantments:mending, still didn't work

Am I stupid and doing something wrong?
Thanks in advance

**Comment by SHsuperCM** [comment] 2022-11-25 09:05
The exact same setup as yours works perfectly fine for me. 
Also your logs are not that useful, you don't seen to be loading the pack in them and there are some errors with other external things.

Try getting the logs again by launching the game, loading the pack and closing the game. Only then send the `latest.log`.

**Comment by yurtema** [comment] 2022-11-30 12:36
Sorry for the delay, i was away from pc. 
[latest.log](https://github.com/SHsuperCM/CITResewn/files/10123168/latest.log) like this?

**Comment by SHsuperCM** [comment] 2023-01-02 15:43
Sorry for the delay.

Dont know what to tell you honestly.. The exact same setup on my end works perfectly fine and your logs dont say anything special about it breaking so everything should be fine in there..
I have to close the issue for now because it is not reproduceable. Do let me know if you find a way to replicate it elsewhere.

**Closed by SHsuperCM** 2023-01-02 15:43 UTC
