### ISSUE TITLE
Backport to 1.20.4

### ISSUE THREAD

**Issue by Murchik0v** [SHsuperCM/CITResewn#374] opened 2024-02-20 05:56 UTC
this mod not working in 1.20.4

**Comment by nco2k** [comment] 2024-03-01 12:06
i understand that it can be annoying for devs to read such requests, but lets not forget that many important mods rely on this one to work.

**Comment by OCTAMIUM** [comment] 2024-03-04 17:50
please update it

**Comment by MuhammadrizoDeveloper** [comment] 2024-03-22 10:58
Pls update it, many mods and resource packs are not working

**Comment by SHsuperCM** [comment] 2024-03-26 12:34
Duplicate of #358 
Do not open extra issues for updating please, all this does is delay the update.

**Closed by SHsuperCM** 2024-03-26 12:34 UTC
Labels: duplicate
