### ISSUE TITLE
Spyglass Texture Error+No Model Overlay

### ISSUE THREAD

**Issue by 0Komentator0** [SHsuperCM/CITResewn#184] opened 2022-08-06 07:27 UTC
I made a model of a telescope for both the item in the slots and in the hand. In the slots, the model seems to be broken. But in the hands the model has not changed at all, can you help? works on optifine
![Снимок экрана (18)](https://user-images.githubusercontent.com/109519330/183239248-d6dddf3b-0a98-4382-8bb3-8e53fb41eb65.png)

**Comment by 0Komentator0** [comment] 2022-08-06 07:28
This testpack is powered by Optifine.

**Comment by SHsuperCM** [comment] 2022-08-08 05:04
Duplicate of #137

**Closed by SHsuperCM** 2022-08-08 05:04 UTC
Labels: duplicate
