### ISSUE TITLE
will there be a mod for version 1.16.5?

### ISSUE THREAD

**Issue by Myskatr** [SHsuperCM/CITResewn#322] opened 2023-09-27 13:45 UTC
Will this mod be available on version 1.16.5, if so, approximately when?

**Comment by SHsuperCM** [comment] 2023-09-28 04:32
![boogy-back](https://github.com/SHsuperCM/CITResewn/assets/22007921/1482d3b6-fb8a-43bb-a271-8e2b11e34c6d)

**Comment by SHsuperCM** [comment] 2023-09-28 04:32
Duplicate of #120

**Closed by SHsuperCM** 2023-09-28 04:32 UTC
