### ISSUE TITLE
Can you add canvas renderer support?

### ISSUE THREAD

**Issue by devinkid1** [SHsuperCM/CITResewn#92] opened 2022-01-10 02:45 UTC
The mod doesnt seem to work with Canvas Renderer, I can send more information if you need anything

**Comment by SHsuperCM** [comment] 2022-01-10 03:06
Duplicate of #83 

> While support for canvas is planned in the future(if still relevant), I currently do not have the capacity to add it with my current schedules. I suggest you switch to sodium as it's built to support much more than canvas.

**Closed by SHsuperCM** 2022-01-10 03:06 UTC
