### ISSUE TITLE
The Spyglass does not appear in the hand

### ISSUE THREAD

**Issue by Vumchak** [SHsuperCM/CITResewn#264] opened 2023-05-16 18:19 UTC
I've already seen issue #137, but unfortunately I didn't quite understand what was going on. So I would be glad if you could explain it to me.
 I have a Spyglass model, it works both in the frame and in the inventory, but it doesn't work in my hands, I have version 1.19.4.
 I will be glad if you can help me.

**Comment by SHsuperCM** [comment] 2023-07-09 06:43
This isnt an issue with packs, it's an issue with CIT Resewn. Opening more issues is not necessary. Spyglasses and tridents will be properly looked at and fixed in due time.

Duplicate of #137

**Closed** 2023-07-09 06:43 UTC
Labels: duplicate
