### ISSUE TITLE
Incompatible with Colormatic

### ISSUE THREAD

**Issue by Feranogame** [SHsuperCM/CITResewn#40] opened 2021-09-26 22:45 UTC
Fails to load certain resourcepacks, such as New Default+, when coupled with Colormatic.

**Comment by SHsuperCM** [comment] 2021-09-27 03:13
Can you send logs?

**Comment by Timolino456** [comment] 2021-09-27 08:58
I have this same issue, but with Iris+Sodium (v1.1.2) and CIT Resewn (0.7.1 and tested with earlier versions aswell) as the only mods installed, since Colormatic is appearently incompatible with Iris and/or Sodium. Only Colormatic and CIT Resewn does not cause this for me. But maybe the problem is the same.
log file with an error:
[latest.log](https://github.com/SHsuperCM/CITResewn/files/7234795/latest.log)

**Comment by SHsuperCM** [comment] 2021-09-27 09:04
@Timolino456 That is not necessarily the same issue, please create a separate issue in situations like these and let authors decide if it's a duplicate issue or not.

In your case, the issue is broken paths. A resourcepack has folders/files that don't follow Minecraft's pack formatting rules. Either fix the resourcepack or enable `Broken Paths` in CIT Resewn's config.

**Comment by kvverti** [comment] 2021-09-27 18:23
The resource pack in question does have broken paths. I could not reproduce the error in a development environment.

**Comment by SHsuperCM** [comment] 2021-09-27 18:25
Ah, then the answer I gave Timolino456 applies to you as well @Feranogame. Closing.

**Comment by SHsuperCM** [comment] 2021-09-27 18:25
I'll reopen if there is actually some incompatibility.

**Closed by SHsuperCM** 2021-09-27 18:25 UTC
Labels: Broken Paths
