### ISSUE TITLE
"exists" syntax does not exist

### ISSUE THREAD

**Issue by naetilus** [SHsuperCM/CITResewn#453] opened 2024-09-08 15:28 UTC
Line: components.minecraft\:written_book_content.generation=exists:false

Optifine behaviour: Checks if item has "generation" component, if it does not, selects the texture.
CIT Resewn behaviour: Does not do anything/ shows vanilla texture

Expected behaviour: Optifine behaviour

**Comment by SHsuperCM** [comment] 2024-09-09 05:18
Duplicate of #204

**Closed by SHsuperCM** 2024-09-09 05:18 UTC
Labels: duplicate
