### ISSUE TITLE
Textures with non [a-z0-9/._-] characters cause pack to fail loading (unlike Optifine)

### ISSUE THREAD

**Issue by BuggyAl** [SHsuperCM/CITResewn#151] opened 2022-06-04 23:38 UTC
I'm not sure how Optifine does it, but I am using NewDefault+ which has a file named `archer's_armor_boots.properties`

While Optifine loads the resource pack perfectly fine, CITResewn doesn't seem to override the limitations. I debated between reporting this to the pack creators and here, and thought that it would be better if it was fixed by this mod for more compatibility.

```
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/icons/minecraft_dungeons/icons_armor/archer's_armor_boots.properties
	at net.minecraft.util.Identifier.<init>(Identifier:41)
	at net.minecraft.util.Identifier.<init>(Identifier:50)
	at net.minecraft.resource.ZipResourcePack.findResources(ZipResourcePack:136)
	at net.minecraft.resource.NamespaceResourceManager.findResources(NamespaceResourceManager:156)
	at net.minecraft.resource.LifecycledResourceManagerImpl.findResources(LifecycledResourceManagerImpl:80)
	at shcm.shsupercm.fabric.citresewn.pack.PackParser.parseCITs(PackParser.java:66)
	at shcm.shsupercm.fabric.citresewn.cit.ActiveCITs.load(ActiveCITs.java:89)
	at net.minecraft.client.render.model.ModelLoader.handler$zbh000$citresewn$loadCITs(ModelLoader:610)
	at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader:190)
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:52)
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:19)
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
```

**Comment by hiisuuii** [comment] 2022-06-05 06:02
Likewise, I am having the same issue with the Ghoulcraft CIT resource pack - it has no issues with Optifine. Error here:
`[00:00:58] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/big green pumpkin.properties
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/big green pumpkin.properties
	at net.minecraft.class_2960.<init>(class_2960.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14408(class_3258.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_3294.method_14488(class_3294.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.method_14488(class_6861.java:80) ~[client-intermediary.jar:?]
	at shcm.shsupercm.fabric.citresewn.pack.PackParser.parseCITs(PackParser.java:66) ~[CITResewn-1.0.1+1.18.2.jar:?]
	at shcm.shsupercm.fabric.citresewn.cit.ActiveCITs.load(ActiveCITs.java:89) ~[CITResewn-1.0.1+1.18.2.jar:?]
	at net.minecraft.class_1088.handler$zze000$citresewn$loadCITs(class_1088.java:610) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.<init>(class_1088.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18178(class_1092.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18789(class_1092.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more`

**Comment by BuggyAl** [comment] 2022-06-05 14:31
In my case, the texture had `'` in the file name while yours included spaces.

**Comment by SHsuperCM** [comment] 2022-06-06 13:09
Very much aware of this, either talk to the pack creator or enable Broken Paths in CIT Resewn's config because this is not something that'll be fixed in an update.

**Closed by SHsuperCM** 2022-06-06 13:09 UTC
Labels: wontfix/intended, Broken Paths
