### ISSUE TITLE
1.19.3 CIT not working for specified items

### ISSUE THREAD

**Issue by ThebestkillerTBK** [SHsuperCM/CITResewn#224] opened 2023-01-03 07:26 UTC
in 1.19.3, potions have null texture

Log:
```
[15:25:25] [Worker-Main-2/INFO]: [citresewn] Linking baked models to item CITs...
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/strength_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/strength_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/luck:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/luck.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_386_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_486_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/slow_falling_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/slow_falling_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/mundane:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/mundane.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/fire_resistance:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/fire_resistance.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/instant_damage:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/instant_damage.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_414_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/mundane:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/mundane.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/night_vision:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/night_vision.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/instant_damage:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/instant_damage.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/poison_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/poison_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/slow_falling_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/slow_falling_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/poison_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/poison_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/invisibility_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/invisibility_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/turtle_master_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/turtle_master_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_472_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/luck:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/luck.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_379_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/jump_boost_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/jump_boost_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/fire_resistance:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/fire_resistance.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/awkward:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/awkward.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_175_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/slowness_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/slowness_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/weakness:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/weakness.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/jump_boost:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/jump_boost.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/strength_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/strength_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/instant_damage:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/instant_damage.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_283_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_127_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/speed_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/speed_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_144_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/slowness:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/slowness.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/invisibility:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/invisibility.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/jump_boost:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/jump_boost.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/slow_falling_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/slow_falling_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_122_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/regeneration_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/regeneration_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/turtle_master_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/turtle_master_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/turtle_master:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/turtle_master.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/strength_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/strength_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_552_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/instant_health:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/instant_health.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/strength:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/strength.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/slow_falling:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/slow_falling.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/regeneration_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/regeneration_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/luck:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/luck.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/speed:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/speed.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/mundane:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/mundane.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/invisibility_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/invisibility_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/regeneration:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/regeneration.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_155_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_445_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/speed_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/speed_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/water_breathing:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/water_breathing.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/regeneration_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/regeneration_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/water_breathing:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/water_breathing.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/slow_falling:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/slow_falling.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/jump_boost:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/jump_boost.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/fire_resistance_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/fire_resistance_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/slowness:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/slowness.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_315_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/thick:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/thick.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/speed:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/speed.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/strength_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/strength_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/regeneration_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/regeneration_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/night_vision:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/night_vision.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/slowness_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/slowness_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/weakness_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/weakness_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/weakness_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/weakness_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_368_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/water_breathing_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/water_breathing_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/slow_falling:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/slow_falling.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/jump_boost_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/jump_boost_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/night_vision_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/night_vision_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/night_vision_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/night_vision_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_460_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_522_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/poison:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/poison.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/speed_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/speed_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/instant_damage_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/instant_damage_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/slowness_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/slowness_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/fire_resistance:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/fire_resistance.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/instant_health_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/instant_health_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/weakness:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/weakness.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_351_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/regeneration_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/regeneration_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_88_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_228_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/turtle_master:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/turtle_master.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/strength_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/strength_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/strength_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/strength_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/water_breathing_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/water_breathing_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/poison_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/poison_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/speed_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/speed_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/poison:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/poison.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/water_breathing:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/water_breathing.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/fire_resistance_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/fire_resistance_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/turtle_master:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/turtle_master.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/regeneration:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/regeneration.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/instant_health:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/instant_health.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/jump_boost_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/jump_boost_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/speed_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/speed_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/instant_damage_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/instant_damage_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/jump_boost_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/jump_boost_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/instant_damage_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/instant_damage_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/night_vision:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/night_vision.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/speed:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/speed.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/poison_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/poison_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/strength:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/strength.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/jump_boost_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/jump_boost_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_35_optifine/cit/enchants/bow/if_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/if_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/night_vision_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/night_vision_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/slowness_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/slowness_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/turtle_master_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/turtle_master_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/speed_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/speed_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/strength:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/strength.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/slowness_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/slowness_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/instant_health:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/instant_health.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/weakness_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/weakness_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_67_optifine/cit/enchants/bow/mf_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/mf_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/regeneration:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/regeneration.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/thick:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/thick.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/slowness:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/slowness.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_467_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/turtle_master_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/turtle_master_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/fire_resistance_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/fire_resistance_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/turtle_master_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/turtle_master_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/turtle_master_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/turtle_master_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/invisibility:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/invisibility.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/poison_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/poison_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/poison:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/poison.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/awkward:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/awkward.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:sub_cititem_generated_21_optifine/cit/enchants/bow/im_s:
    minecraft:textures/atlas/blocks.png:minecraft:optifine/cit/enchants/bow/im_s.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/regeneration_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/regeneration_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/instant_health_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/instant_health_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/awkward:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/awkward.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/poison_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/poison_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/invisibility_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/invisibility_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/slowness_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/slowness_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/invisibility:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/invisibility.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/instant_health_strong:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/instant_health_strong.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/weakness:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/weakness.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/linger/models/thick:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/linger/thick.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/normal/models/jump_boost_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/normal/jump_boost_long.png
[15:25:25] [Worker-Main-2/WARN]: Missing textures in model minecraft:optifine/cit/potions/splash/models/water_breathing_long:
    minecraft:textures/atlas/blocks.png:minecraft:textures/potions/splash/water_breathing_long.png
```

**Comment by SHsuperCM** [comment] 2023-01-03 07:40
Going to need the full logs file as well as the resourcepack this is happening on

**Comment by ThebestkillerTBK** [comment] 2023-01-03 08:35
[log](https://mclo.gs/c4SAVuU)
[resource pack](https://www.curseforge.com/minecraft/texture-packs/xekr-redstone-display)

**Comment by SHsuperCM** [comment] 2023-01-03 08:44
The potion textures are not in the atlas, this is a vanilla thing, not cit(they havent properly updated the pack).
Tell the pack author to add `potions` folder to the atlas if they want the textures in there to work in 1.19.3.

Also kinda duplicate of #223 because it's a textures directory that pack authors haven't put in an atlas.

**Closed by SHsuperCM** 2023-01-03 08:44 UTC
Labels: User Error
