### ISSUE TITLE
Loading CIT Items takes upwards of 3 minutes on 1.19

### ISSUE THREAD

**Issue by PINPAL** [SHsuperCM/CITResewn#173] opened 2022-07-11 10:52 UTC
### Log
See timestamps for time reference.
```
[11:44:28] [Worker-Main-31/INFO]: [citresewn] Loading item CIT models...
[11:47:28] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[11:47:28] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[11:47:28] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on DAC X6-MKII (FX-AUDIO)
[11:47:28] [Render thread/INFO]: Sound engine started
[11:47:28] [Render thread/INFO]: Created: 2048x1024x3 minecraft:textures/atlas/blocks.png-atlas
[11:47:28] [Render thread/INFO]: Created: 256x128x3 minecraft:textures/atlas/signs.png-atlas
[11:47:28] [Render thread/INFO]: Created: 1024x512x3 minecraft:textures/atlas/banner_patterns.png-atlas
[11:47:28] [Render thread/INFO]: Created: 2048x1024x3 minecraft:textures/atlas/shield_patterns.png-atlas
[11:47:28] [Render thread/INFO]: Created: 256x256x3 minecraft:textures/atlas/chest.png-atlas
[11:47:28] [Render thread/INFO]: Created: 512x256x3 minecraft:textures/atlas/beds.png-atlas
[11:47:28] [Render thread/INFO]: Created: 512x256x3 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:47:28] [Render thread/INFO]: [citresewn] Linking baked models to item CITs...
[11:47:29] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[11:47:29] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[11:47:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:47:29] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
```

**Packs in Question**
https://www.curseforge.com/minecraft/texture-packs/obvious-item-filters
https://www.curseforge.com/minecraft/texture-packs/unique-books
https://www.curseforge.com/minecraft/texture-packs/unique-potions

### System Specs
**CPU:** i9 10900K
**GPU:** RTX 2070 Super
**RAM:** 16GB 4000MHz CL16 (10GB Allocated)

### Additional Info
I have update my packs for 1.19 but noticed they are taking extremely long to load in 1.19?
Is there an optimisation trick I have missed or something that has changed in 1.19? I couldn't find anything in the docs relating to this so any information is appreciated. Thanks.

**Comment by SHsuperCM** [comment] 2022-07-11 11:23
Duplicate of #159 

Essentially a vanilla bug that was apparently fixed during 1.19.1's development.

**Closed by SHsuperCM** 2022-07-11 11:23 UTC
Labels: duplicate
