### ISSUE TITLE
Spyglass

### ISSUE THREAD

**Issue by JaredHuh** [SHsuperCM/CITResewn#190] opened 2022-08-21 00:37 UTC
There is a problem that spyglass with custom texture in itemframe is displayed incorrectly, and in the hand looks like a default spyglass.

Images:
https://imgur.com/hfhoZ2W
https://imgur.com/aJutqq5

Thank you in advance!

**Comment by SHsuperCM** [comment] 2022-08-21 04:05
Duplicate of #137

**Closed** 2022-08-21 04:05 UTC
Labels: duplicate
