### ISSUE TITLE
Loaded Crossbow Textures Uses Standby Texture

### ISSUE THREAD

**Issue by spxctreofficial** [SHsuperCM/CITResewn#86] opened 2021-12-27 16:42 UTC
I'm not sure if this is a duplicate of #65 or #81, but I'm trying to create a custom item texture for the crossbow and while everything else works, when the crossbow is loaded with the arrow it shows the standby texture, and when the crossbow is loaded with fireworks it shows the arrow texture. Any idea as to what the issue is or a workaround?

```
type=item
items=minecraft:crossbow
texture.crossbow=tactical_standby
texture.crossbow_arrow=tactical_arrow
texture.crossbow_firework=tactical_firework
texture.crossbow_pulling_0=tactical_pulling_0
texture.crossbow_pulling_1=tactical_pulling_1
texture.crossbow_pulling_2=tactical_pulling_2
nbt.display.Name=test
```

**Comment by SHsuperCM** [comment] 2021-12-27 16:52
Duplicate of #81

**Closed** 2021-12-27 16:53 UTC
Labels: duplicate
