### ISSUE TITLE
Release compatible with 1.17.1?

### ISSUE THREAD

**Issue by StickyChannel92** [SHsuperCM/CITResewn#133] opened 2022-04-19 17:45 UTC
I only use 1.17.1 because I'm afraid if I switch versions, I would lose half or most, if not all, my mods.

Can I get a custom release for 1.17.1 compatibility? Or is it compatible with Java 16 or 17 and I can change numbers in the files from 1.18 to 1.17.1 and if so, which files and strings do I change?

**Comment by SHsuperCM** [comment] 2022-04-20 04:33
Duplicate of #120

**Closed by SHsuperCM** 2022-04-20 04:33 UTC
Labels: duplicate
