### ISSUE TITLE
Sorry For The Second Issue I meant to Say Francium But I Mistakenly Wrote Fracium

### ISSUE THREAD

**Issue by akasaitama** [SHsuperCM/CITResewn#413] opened 2024-06-17 11:16 UTC
i tried it on 3 devices still it's not working I pressed equal nothing happens,menu didn't came this only happened today I am using francium since 6 months it's worked perfectly but idk why when I wake up I open Minecraft and press equal the menu didn't show for me

**Comment by SHsuperCM** [comment] 2024-06-17 11:29
Dont make multiple issues

**Comment by SHsuperCM** [comment] 2024-06-17 11:29
Duplicate of #411

**Closed by SHsuperCM** 2024-06-17 11:29 UTC
Labels: duplicate, invalid
