### ISSUE TITLE
Renamed spyglasses are looking incorrectly

### ISSUE THREAD

**Issue by BezShkvark0** [SHsuperCM/CITResewn#292] opened 2023-07-18 19:05 UTC
When you are changing spyglasses using CIT recoursepacks by changing in .properties both model and texture, and while you use optifine everything works smooth and well but in case of using CIT Resewn spyglass gets inventory item texture as it's model texture.
![image](https://github.com/SHsuperCM/CITResewn/assets/66226616/ee5ea189-0244-48d3-807c-240fc3586f9b)
properties file screenshot
![image1](https://github.com/SHsuperCM/CITResewn/assets/66226616/ddf259d1-40ce-4089-8139-807eda880c90)
in-game screenshot
![image](https://github.com/SHsuperCM/CITResewn/assets/66226616/21039911-de5f-46e4-835b-29e2dd394bd1)
that's how it is supposed to be(and it is when you're using optifine). Left item frame - The way it supposed to look in inventory. Right item frame - model that is supposed to be.

**Comment by SHsuperCM** [comment] 2023-07-22 06:23
Duplicate of #137

**Closed by SHsuperCM** 2023-07-22 06:23 UTC
Labels: duplicate
